# Generated by Django 4.2.6 on 2023-10-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='my_custom_table_name',
        ),
    ]
