# Generated by Django 4.2.6 on 2023-10-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_actor_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['gender']},
        ),
        migrations.AlterModelTable(
            name='actor',
            table=None,
        ),
    ]
